#ifndef SRC_LIB_NRL_VERSION_H
#define SRC_LIB_NRL_VERSION_H

#define NRL_FIRMWARE_VERSION "0.0.1"
#define NRL_FIRMWARE_NAME "NRL3188-ESP32"
#define NRL_FIRMWARE_BANNER NRL_FIRMWARE_NAME " v" NRL_FIRMWARE_VERSION

#endif // SRC_LIB_NRL_VERSION_H
