[platformio]
src_dir = src

[env:app0_main]
platform = espressif32@6.9.0
board = adafruit_qtpy_esp32s3_n4r2
framework = arduino
monitor_speed = 115200
board_build.partitions = part.csv
board_build.app_partition = app0
upload_protocol = esptool
upload_speed = 921600
extra_scripts =
    scripts/generate_wifi_portal_html.py
    scripts/fix_size_per_env.py
build_src_filter =
    -<*>
    +<app/main.cpp>
    +<app/driver/eeprom.cpp>
    +<app/driver/es8311.cpp>
    +<app/driver/external_radio.cpp>
    +<app/driver/i2c.cpp>
    +<app/driver/sci_serial.cpp>
    +<app/driver/status_io.cpp>
    +<lib/nrl_at_commands.cpp>
    +<lib/nrl_audio_bridge.cpp>
    +<lib/ble_config.cpp>
    +<lib/wifi_config_portal.cpp>
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -fextended-identifiers
    -finput-charset=UTF-8
    -fexec-charset=UTF-8
    -Isrc/app
    -Isrc/app/driver
    -Isrc/lib
