const translations={
en:{language:'Language',wifiConfig:'WiFi Config',nrlConfig:'NRL Config',audioSettings:'Audio Settings',firmwareUpdate:'Firmware Update',configAp:'Config AP',stationIp:'Station IP',firmwareVersion:'Firmware version',updateHeadline:'Firmware Update',updateIntro:'Upload a firmware file over this WiFi connection.',updateDoneHeadline:'Update Complete',updateDoneIntro:'Firmware was written successfully. Rebooting shortly.',updateFailHeadline:'Update Failed',updateFailIntro:'Firmware upload failed. Check that the file is a valid firmware.bin.',otaNotice:'Select a firmware.bin file from support or from a trusted release. The device will reboot after a successful update.',remoteOtaTitle:'Remote OTA',remoteOtaIntro:'The device periodically reports its board, firmware, NRL callsign and SSID to the HTTPS OTA server. Only firmware built for this board is listed.',otaServerUrl:'OTA server URL (HTTPS)',deviceAccessToken:'Device access token (optional)',saveOtaServer:'Save OTA server',checkReleases:'Check releases',remoteNotConfigured:'Not configured',availableVersions:'Available versions',checkReleasesFirst:'Check releases first',selectVersion:'Select a version',noCompatibleReleases:'No compatible releases were returned.',installSelectedVersion:'Install selected version',remoteWorking:'Working...',remoteLatest:'Latest version: {version}',none:'none',remoteSavedChecking:'Saved. Checking releases...',remoteChecking:'Checking releases...',confirmInstall:'Install {version}? The device will reboot.',remoteDownloading:'Downloading firmware. The device will reboot.',remoteError:'Error: {error}',requestFailed:'Request failed',useHttpsServerUrl:'Use an HTTPS OTA server URL. The address was not saved.',configureOtaFirst:'Configure the OTA server first.',selectReleasedVersion:'Select a released version.',otaTitle:'WiFi Firmware Update',uploadFirmware:'Upload firmware',otaUploading:'Uploading firmware...',otaInstalling:'Installing firmware, please wait...',otaDone:'Update complete. Device is rebooting.',otaRebooting:'Waiting for device to come back online...',otaRebooted:'Device is back online. Update finished.',otaRebootTimeout:'Could not reach the device. Please check it manually.',otaFailed:'Update failed. Please try again.'},
zh:{language:'语言',wifiConfig:'WiFi配置',nrlConfig:'NRL配置',audioSettings:'音频设置',firmwareUpdate:'固件升级',configAp:'配置热点',stationIp:'联网地址',firmwareVersion:'固件版本',updateHeadline:'固件升级',updateIntro:'通过当前 WiFi 配置页面上传固件文件。',updateDoneHeadline:'升级完成',updateDoneIntro:'固件写入成功，设备即将重启。',updateFailHeadline:'升级失败',updateFailIntro:'固件上传失败，请确认文件是有效的 firmware.bin。',otaNotice:'请选择来自官方发布或售后支持的 firmware.bin 文件。升级成功后设备会自动重启。',remoteOtaTitle:'远程 OTA 升级',remoteOtaIntro:'设备会定期向 HTTPS OTA 服务器报告板卡、固件版本、NRL 呼号和 SSID，并且只显示适用于当前板卡的固件。',otaServerUrl:'OTA 服务器地址（HTTPS）',deviceAccessToken:'设备访问令牌（可选）',saveOtaServer:'保存 OTA 服务器',checkReleases:'检查版本',remoteNotConfigured:'尚未配置',availableVersions:'可用版本',checkReleasesFirst:'请先检查版本',selectVersion:'选择版本',noCompatibleReleases:'服务器没有返回适用于当前板卡的版本。',installSelectedVersion:'安装选中版本（可升级或回退）',remoteWorking:'正在处理...',remoteLatest:'最新版本：{version}',none:'无',remoteSavedChecking:'已保存，正在检查版本...',remoteChecking:'正在检查版本...',confirmInstall:'确定安装 {version} 吗？设备将会重启。',remoteDownloading:'正在下载固件，设备将会重启。',remoteError:'错误：{error}',requestFailed:'请求失败',useHttpsServerUrl:'请输入 HTTPS OTA 服务器地址，当前地址没有保存。',configureOtaFirst:'请先配置 OTA 服务器。',selectReleasedVersion:'请选择已发布的固件版本。',otaTitle:'WiFi固件升级',uploadFirmware:'上传固件',otaUploading:'正在上传固件...',otaInstalling:'正在升级，请稍候...',otaDone:'升级完成，设备正在重启。',otaRebooting:'正在等待设备重新启动...',otaRebooted:'设备已重启完成，升级成功。',otaRebootTimeout:'无法连接到设备，请手动检查。',otaFailed:'升级失败，请重试。'}
};
Object.assign(translations.en,{remoteOtaIntro:'The device periodically reports its board, firmware, NRL callsign and SSID to the OTA server. HTTP is intended only for a trusted LAN; HTTPS is recommended otherwise.',otaServerUrl:'OTA server URL (HTTP/HTTPS)',useHttpsServerUrl:'Use an HTTP or HTTPS OTA server URL. The address was not saved.'});
Object.assign(translations.zh,{remoteOtaIntro:'设备会定期向 OTA 服务器报告板卡、固件版本、NRL 呼号和 SSID，并且只显示适用于当前板卡的固件。HTTP 仅建议在可信局域网使用，其他环境请使用 HTTPS。',otaServerUrl:'OTA 服务器地址（HTTP/HTTPS）',useHttpsServerUrl:'请输入 HTTP 或 HTTPS OTA 服务器地址，当前地址没有保存。'});
Object.assign(translations.en,{mediaConfig:'Media / Nanny',aprsConfig:'APRS'});
Object.assign(translations.zh,{mediaConfig:'媒体/保姆',aprsConfig:'APRS'});
Object.assign(translations.en,{signalingConfig:'Signaling / CTCSS'});
Object.assign(translations.zh,{signalingConfig:'信令 / CTCSS'});
Object.assign(translations.en,{remoteUpdating:'Installing firmware... {percent}%'});
Object.assign(translations.en,{releaseTitle:'0.8.5 feature updates',releaseMicGain:'Adds configurable 0.1-5.0x microphone PCM gain through Web and AT commands, with runtime ES7210 gain updates.',releaseGpsUart:'Allows pins from a disabled serial port to be reassigned, including Gezipai GPIO43/44 for GPS.',releaseGpsAprs:'Adds GPS satellite count and standard APRS speed, course, and altitude reporting.',releaseAprsRows:'Organizes APRS-IS information into navigation and device rows, hiding GPS fields when no fix is available.'});
Object.assign(translations.zh,{releaseTitle:'0.8.5 功能更新',releaseMicGain:'新增可通过 Web 和 AT 指令配置的 0.1-5.0 倍麦克风 PCM 增益，并支持运行时更新 ES7210 增益。',releaseGpsUart:'允许复用已停用串口的引脚，包括将格子派 GPIO43/44 改作 GPS 串口。',releaseGpsAprs:'新增 GPS 卫星数量以及 APRS 标准速度、航向和海拔上报。',releaseAprsRows:'APRS-IS 信息按定位与设备两行组织，无定位时隐藏 GPS 相关字段。'});
Object.assign(translations.zh,{remoteUpdating:'正在升级固件... {percent}%'});
function lang(){const s=localStorage.getItem('nrl_lang');if(s==='zh'||s==='en')return s;return navigator.language&&navigator.language.toLowerCase().startsWith('zh')?'zh':'en';}
function t(k,values={}){const l=lang();let text=(translations[l]&&translations[l][k])||translations.en[k]||k;Object.entries(values).forEach(([name,value])=>{text=text.replace('{'+name+'}',String(value));});return text;}
function localizeApiError(message){const keys={'Use an HTTPS server URL':'useHttpsServerUrl','Use an HTTP or HTTPS server URL':'useHttpsServerUrl','Configure the OTA server first':'configureOtaFirst','Select a released version':'selectReleasedVersion','Request failed':'requestFailed'};return keys[message]?t(keys[message]):message;}

let otaCurrentKey=null,otaCurrentPct=null,lastRemoteStatus=null,remoteMessage=null;
function applyLanguage(l){localStorage.setItem('nrl_lang',l);document.documentElement.lang=l==='zh'?'zh-CN':'en';document.querySelectorAll('input[name="lang"]').forEach((r)=>{r.checked=(r.value===l);});document.querySelectorAll('[data-i18n]').forEach((el)=>{const k=el.getAttribute('data-i18n');if(translations[l]&&translations[l][k])el.textContent=translations[l][k];});const heading=document.querySelector('h1');if(heading)document.title=heading.textContent;if(otaCurrentKey)setOta(otaCurrentKey,otaCurrentPct);renderRemote();}

const otaForm=document.getElementById('ota-form'),otaFile=document.getElementById('ota-file'),otaSubmit=document.getElementById('ota-submit'),otaProgress=document.getElementById('ota-progress'),otaBar=document.getElementById('ota-bar'),otaStatus=document.getElementById('ota-status');
function setOta(k,p){otaCurrentKey=k;otaCurrentPct=(p==null?null:p);otaStatus.removeAttribute('data-i18n');otaStatus.textContent=(p==null)?t(k):(t(k)+' '+p+'%');}
function pollAlive(){let n=0;const max=30;const tick=()=>{if(n>=max){setOta('otaRebootTimeout',null);return;}n++;const c=new AbortController();const tm=setTimeout(()=>c.abort(),1500);fetch('/ping?_='+Date.now(),{cache:'no-store',signal:c.signal}).then((r)=>{clearTimeout(tm);if(r.ok){setOta('otaRebooted',null);}else{setTimeout(tick,2000);}}).catch(()=>{clearTimeout(tm);setTimeout(tick,2000);});};setTimeout(tick,3000);}
if(otaForm){otaForm.addEventListener('submit',function(e){e.preventDefault();const f=otaFile.files&&otaFile.files[0];if(!f)return;otaSubmit.disabled=true;otaProgress.hidden=false;otaBar.classList.remove('done','failed');otaBar.style.width='0%';setOta('otaUploading',0);const xhr=new XMLHttpRequest();xhr.upload.onprogress=function(ev){if(ev.lengthComputable){const pct=Math.floor(ev.loaded*100/ev.total);otaBar.style.width=pct+'%';setOta('otaUploading',pct);}};xhr.upload.onload=function(){otaBar.style.width='100%';setOta('otaInstalling',null);};xhr.onload=function(){if(xhr.status===200){otaBar.style.width='100%';otaBar.classList.add('done');setOta('otaRebooting',null);pollAlive();}else{otaBar.classList.add('failed');setOta('otaFailed',null);otaSubmit.disabled=false;}};xhr.onerror=function(){otaBar.classList.add('failed');setOta('otaFailed',null);otaSubmit.disabled=false;};xhr.open('POST','/update');xhr.setRequestHeader('Content-Type','application/octet-stream');xhr.send(f);});}

const remoteConfig=document.getElementById('remote-ota-config'),remoteUrl=document.getElementById('ota-server-url'),remoteToken=document.getElementById('ota-device-token'),remoteStatus=document.getElementById('remote-ota-status'),remoteProgress=document.getElementById('remote-ota-progress'),remoteBar=document.getElementById('remote-ota-bar'),releaseList=document.getElementById('ota-release-list'),checkRemote=document.getElementById('ota-check'),installRemote=document.getElementById('ota-install');
let remotePollTimer=null,remotePollUntil=0,remoteInstallPolling=false,remoteSawUpdating=false;
async function remotePost(path,data){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(data)});const v=await r.json().catch(()=>({error:t('requestFailed')}));if(!r.ok)throw new Error(v.error||t('requestFailed'));return v;}
function renderReleaseList(){if(!releaseList)return;const selected=releaseList.value;const releases=(lastRemoteStatus&&lastRemoteStatus.releases)||[];releaseList.innerHTML='';const first=document.createElement('option');first.value='';first.textContent=releases.length?t('selectVersion'):((lastRemoteStatus&&lastRemoteStatus.last_check_ms)?t('noCompatibleReleases'):t('checkReleasesFirst'));releaseList.appendChild(first);releases.forEach((release)=>{const option=document.createElement('option');option.value=release.version;option.textContent=release.version+(release.notes?' — '+release.notes:'');releaseList.appendChild(option);});releaseList.value=selected;const busy=!!(lastRemoteStatus&&(lastRemoteStatus.checking||lastRemoteStatus.updating))||remoteInstallPolling;installRemote.disabled=busy||!releaseList.value;}
function renderRemote(){
  if(!remoteStatus)return;
  const updating=!!(lastRemoteStatus&&lastRemoteStatus.updating);
  const progressKnown=updating&&Number(lastRemoteStatus.update_size)>0;
  const percent=progressKnown?Math.max(0,Math.min(100,Number(lastRemoteStatus.update_percent)||0)):0;
  if(remoteProgress)remoteProgress.hidden=!progressKnown;
  if(remoteBar)remoteBar.style.width=percent+'%';
  if(remoteMessage)remoteStatus.textContent=t(remoteMessage.key,remoteMessage.values);
  else if(lastRemoteStatus&&lastRemoteStatus.last_error)remoteStatus.textContent=t('remoteError',{error:localizeApiError(lastRemoteStatus.last_error)});
  else if(!lastRemoteStatus||!lastRemoteStatus.configured)remoteStatus.textContent=t('remoteNotConfigured');
  else if(progressKnown)remoteStatus.textContent=t('remoteUpdating',{percent});
  else if(lastRemoteStatus.checking||updating)remoteStatus.textContent=t('remoteWorking');
  else remoteStatus.textContent=t('remoteLatest',{version:lastRemoteStatus.latest_version||t('none')});
  const configured=!!(lastRemoteStatus&&lastRemoteStatus.configured);
  checkRemote.disabled=!configured||!!(lastRemoteStatus&&(lastRemoteStatus.checking||lastRemoteStatus.updating))||remoteInstallPolling;
  if(remoteUrl&&configured)remoteUrl.value=lastRemoteStatus.server_url;
  renderReleaseList();
}
function showRemote(status){
  lastRemoteStatus=status;
  if(remoteInstallPolling){
    if(status.updating){remoteSawUpdating=true;remoteMessage=null;}
    else if(status.last_error||(remoteSawUpdating&&!status.updating)){
      remoteInstallPolling=false;
      remotePollUntil=0;
      remoteMessage=null;
    }
  }else remoteMessage=null;
  renderRemote();
}
function setRemoteMessage(key,values={}){remoteMessage={key,values};renderRemote();}
function scheduleRemoteRefresh(delay=1000){if(remotePollTimer)clearTimeout(remotePollTimer);remotePollTimer=setTimeout(refreshRemote,delay);}
function startRemotePolling(duration=20000){remotePollUntil=Date.now()+duration;scheduleRemoteRefresh(500);}
async function refreshRemote(){try{const r=await fetch('/ota/status',{cache:'no-store'});if(!r.ok)throw new Error(t('requestFailed'));showRemote(await r.json());}catch(error){if(remoteInstallPolling){remoteSawUpdating=true;setRemoteMessage('otaRebooting');}else setRemoteMessage('remoteError',{error:localizeApiError(error.message)});}finally{if(Date.now()<remotePollUntil)scheduleRemoteRefresh();}}
if(remoteConfig)remoteConfig.addEventListener('submit',async(e)=>{e.preventDefault();const serverUrl=remoteUrl.value.trim();const scheme=serverUrl.toLowerCase();if(!scheme.startsWith('http://')&&!scheme.startsWith('https://')){setRemoteMessage('remoteError',{error:t('useHttpsServerUrl')});remoteUrl.focus();return;}try{await remotePost('/ota/config',{server_url:serverUrl,device_token:remoteToken.value});setRemoteMessage('remoteSavedChecking');await remotePost('/ota/check',{});startRemotePolling();}catch(error){setRemoteMessage('remoteError',{error:localizeApiError(error.message)});}});
if(checkRemote)checkRemote.addEventListener('click',async()=>{try{await remotePost('/ota/check',{});setRemoteMessage('remoteChecking');startRemotePolling();}catch(error){setRemoteMessage('remoteError',{error:localizeApiError(error.message)});}});
if(installRemote)installRemote.addEventListener('click',async()=>{const version=releaseList.value;if(!version)return;if(!confirm(t('confirmInstall',{version})))return;try{await remotePost('/ota/install',{version});remoteInstallPolling=true;remoteSawUpdating=false;setRemoteMessage('remoteDownloading');startRemotePolling(300000);}catch(error){setRemoteMessage('remoteError',{error:localizeApiError(error.message)});}});
if(releaseList)releaseList.addEventListener('change',()=>{const busy=!!(lastRemoteStatus&&(lastRemoteStatus.checking||lastRemoteStatus.updating))||remoteInstallPolling;installRemote.disabled=busy||!releaseList.value;});

applyLanguage(lang());
document.querySelectorAll('input[name="lang"]').forEach((radio)=>{radio.addEventListener('change',function(){if(this.checked)applyLanguage(this.value);});});
refreshRemote();
