const translations={en:{language:'Language',wifiConfig:'WiFi Config',nrlConfig:'NRL Config',audioSettings:'Audio Settings',firmwareUpdate:'Firmware Update',configAp:'Config AP',stationIp:'Station IP',firmwareVersion:'Firmware version',updateHeadline:'Firmware Update',updateIntro:'Upload a firmware file over this WiFi connection.',updateDoneHeadline:'Update Complete',updateDoneIntro:'Firmware was written successfully. Rebooting shortly.',updateFailHeadline:'Update Failed',updateFailIntro:'Firmware upload failed. Check that the file is a valid firmware.bin.',otaNotice:'Select a firmware.bin file from support or from a trusted release. The device will reboot after a successful update.',otaTitle:'WiFi Firmware Update',uploadFirmware:'Upload firmware',otaUploading:'Uploading firmware...',otaInstalling:'Installing firmware, please wait...',otaDone:'Update complete. Device is rebooting.',otaRebooting:'Waiting for device to come back online...',otaRebooted:'Device is back online. Update finished.',otaRebootTimeout:'Could not reach the device. Please check it manually.',otaFailed:'Update failed. Please try again.'},zh:{language:'语言',wifiConfig:'WiFi配置',nrlConfig:'NRL配置',audioSettings:'音频设置',firmwareUpdate:'固件升级',configAp:'配置热点',stationIp:'联网地址',firmwareVersion:'固件版本',updateHeadline:'固件升级',updateIntro:'通过当前 WiFi 配置页面上传固件文件。',updateDoneHeadline:'升级完成',updateDoneIntro:'固件写入成功，设备即将重启。',updateFailHeadline:'升级失败',updateFailIntro:'固件上传失败，请确认文件是有效的 firmware.bin。',otaNotice:'请选择来自官方发布或售后支持的 firmware.bin 文件。升级成功后设备会自动重启。',otaTitle:'WiFi固件升级',uploadFirmware:'上传固件',otaUploading:'正在上传固件...',otaInstalling:'正在升级，请稍候...',otaDone:'升级完成，设备正在重启。',otaRebooting:'正在等待设备重新启动...',otaRebooted:'设备已重启完成，升级成功。',otaRebootTimeout:'无法连接到设备，请手动检查。',otaFailed:'升级失败，请重试。'}};
function lang(){const s=localStorage.getItem('nrl_lang');if(s==='zh'||s==='en')return s;return navigator.language&&navigator.language.toLowerCase().startsWith('zh')?'zh':'en';}
function t(k){const l=lang();return (translations[l]&&translations[l][k])||translations.en[k]||k;}
function applyLanguage(l){localStorage.setItem('nrl_lang',l);document.documentElement.lang=l==='zh'?'zh-CN':'en';document.querySelectorAll('input[name="lang"]').forEach((r)=>{r.checked=(r.value===l);});document.querySelectorAll('[data-i18n]').forEach((el)=>{const k=el.getAttribute('data-i18n');if(translations[l]&&translations[l][k])el.textContent=translations[l][k];});if(otaCurrentKey){setOta(otaCurrentKey,otaCurrentPct);}}
let otaCurrentKey=null,otaCurrentPct=null;
const otaForm=document.getElementById('ota-form'),otaFile=document.getElementById('ota-file'),otaSubmit=document.getElementById('ota-submit'),otaProgress=document.getElementById('ota-progress'),otaBar=document.getElementById('ota-bar'),otaStatus=document.getElementById('ota-status');
function setOta(k,p){otaCurrentKey=k;otaCurrentPct=(p==null?null:p);otaStatus.removeAttribute('data-i18n');otaStatus.textContent=(p==null)?t(k):(t(k)+' '+p+'%');}
function pollAlive(){let n=0;const max=30;const tick=()=>{if(n>=max){setOta('otaRebootTimeout',null);return;}n++;const c=new AbortController();const tm=setTimeout(()=>c.abort(),1500);fetch('/ping?_='+Date.now(),{cache:'no-store',signal:c.signal}).then((r)=>{clearTimeout(tm);if(r.ok){setOta('otaRebooted',null);}else{setTimeout(tick,2000);}}).catch(()=>{clearTimeout(tm);setTimeout(tick,2000);});};setTimeout(tick,3000);}
if(otaForm){otaForm.addEventListener('submit',function(e){e.preventDefault();const f=otaFile.files&&otaFile.files[0];if(!f)return;otaSubmit.disabled=true;otaProgress.hidden=false;otaBar.classList.remove('done','failed');otaBar.style.width='0%';setOta('otaUploading',0);const xhr=new XMLHttpRequest();xhr.upload.onprogress=function(ev){if(ev.lengthComputable){const pct=Math.floor(ev.loaded*100/ev.total);otaBar.style.width=pct+'%';setOta('otaUploading',pct);}};xhr.upload.onload=function(){otaBar.style.width='100%';setOta('otaInstalling',null);};xhr.onload=function(){if(xhr.status===200){otaBar.style.width='100%';otaBar.classList.add('done');setOta('otaRebooting',null);pollAlive();}else{otaBar.classList.add('failed');setOta('otaFailed',null);otaSubmit.disabled=false;}};xhr.onerror=function(){otaBar.classList.add('failed');setOta('otaFailed',null);otaSubmit.disabled=false;};xhr.open('POST','/update');xhr.setRequestHeader('Content-Type','application/octet-stream');xhr.send(f);});}
applyLanguage(lang());document.querySelectorAll('input[name="lang"]').forEach((r)=>{r.addEventListener('change',function(){if(this.checked)applyLanguage(this.value);});});
