#!/usr/bin/env python3
"""Generate LVGL v9 bitmap fonts with the common Chinese character set.

Renders GB2312 level-1 hanzi (3755 chars, covers ~99.7% of modern text) plus
CJK punctuation and fullwidth forms from Noto Sans SC into LVGL
lv_font_fmt_txt C sources (4bpp, plain format -- byte-identical layout to the
lv_font_conv output used for the bundled Montserrat fonts).

The fonts are used as `fallback` of the Montserrat fonts on the S31 LCD, so
ASCII keeps the Latin design and only CJK glyphs come from here.

Usage (Pillow required):
    python scripts/gen_cjk_font.py            # writes src/app/driver/fonts/

The source TTF is downloaded into scripts/cache/ on first run (Noto Sans SC,
SIL Open Font License 1.1).
"""
import io
import os
import sys
import urllib.request
from pathlib import Path

from PIL import Image, ImageFont

REPO = Path(__file__).resolve().parent.parent
CACHE = REPO / "scripts" / "cache"
OUT_DIR = REPO / "src" / "app" / "driver" / "fonts"
FONT_URL = ("https://github.com/notofonts/noto-cjk/raw/main/Sans/SubsetOTF/SC/"
            "NotoSansSC-Regular.otf")
FONT_FILE = CACHE / "NotoSansSC-Regular.otf"
SIZES = (16, 20)
BPP = 4


def gb2312_level1_chars():
    """The 3755 level-1 hanzi: GB2312 rows 16-55 (0xB0-0xD7)."""
    chars = []
    for hi in range(0xB0, 0xD8):
        for lo in range(0xA1, 0xFF):
            try:
                ch = bytes((hi, lo)).decode("gb2312")
                chars.append(ch)
            except UnicodeDecodeError:
                continue
    return chars


def punctuation_chars():
    general = "‘’“”—…·※"                       # U+2000 block
    cjk_symbols = "、。〃〈〉《》「」『』【】〔〕　"  # U+3000 block (incl. ideographic space)
    fullwidth = "".join(chr(cp) for cp in range(0xFF01, 0xFF5F))  # ！ .. ｝
    return general + cjk_symbols + fullwidth


def collect_glyphs(font, chars):
    """Rasterize every char; returns list of dicts sorted by codepoint."""
    ascent, descent = font.getmetrics()
    glyphs = []
    for ch in sorted(set(chars), key=ord):
        try:
            mask, offset = font.getmask2(ch, mode="L")
        except Exception:
            continue
        w, h = mask.size
        adv = max(0, round(font.getlength(ch) * 16))
        if w == 0 or h == 0:
            glyphs.append(dict(cp=ord(ch), adv=adv, w=0, h=0, ox=0, oy=0, bits=b""))
            continue
        raw = Image.Image()._new(mask).tobytes()  # 8-bit rows
        # Pack the whole glyph as one continuous 4-bit stream (no row pad).
        nibbles = []
        for y in range(h):
            for x in range(w):
                nibbles.append(raw[y * w + x] >> 4)
        if len(nibbles) % 2:
            nibbles.append(0)
        bits = bytes((nibbles[i] << 4) | nibbles[i + 1] for i in range(0, len(nibbles), 2))
        ox, oy_top = offset
        oy = ascent - (oy_top + h)  # bottom of bbox relative to baseline
        glyphs.append(dict(cp=ord(ch), adv=adv, w=w, h=h, ox=ox, oy=oy, bits=bits))
    return glyphs, ascent, descent


def build_cmaps(glyphs):
    """Group codepoints into cmap blocks (SPARSE_TINY needs uint16 offsets)."""
    blocks = [(0x2000, 0x206F), (0x3000, 0x303F), (0x4E00, 0x9FFF), (0xFF00, 0xFFEF)]
    cmaps = []
    glyph_id = 1
    ordered = []
    for start, end in blocks:
        members = [g for g in glyphs if start <= g["cp"] <= end]
        if not members:
            continue
        offsets = [g["cp"] - start for g in members]
        cmaps.append(dict(range_start=start,
                          range_length=offsets[-1] + 1,
                          glyph_id_start=glyph_id,
                          offsets=offsets))
        ordered.extend(members)
        glyph_id += len(members)
    return cmaps, ordered


def emit_c(name, size, glyphs, cmaps, ascent, descent):
    out = io.StringIO()
    ident = name
    out.write(f"""/* Auto-generated by scripts/gen_cjk_font.py -- DO NOT EDIT.
 * Source: Noto Sans SC Regular (SIL OFL 1.1), size {size}px, bpp {BPP}.
 * GB2312 level-1 hanzi + CJK punctuation + fullwidth forms
 * ({len(glyphs)} glyphs). Used as fallback of the Montserrat fonts so ASCII
 * stays Latin-designed and only CJK comes from here. */
#include "driver/board_pins.h"
#if NRL_BOARD == NRL_BOARD_S31_KORVO
#include <lvgl.h>

static LV_ATTRIBUTE_LARGE_CONST const uint8_t glyph_bitmap[] = {{
""")
    index = 0
    indices = []
    for g in glyphs:
        indices.append(index)
        bits = g["bits"]
        if bits:
            out.write(f"    /* U+{g['cp']:04X} */\n")
            for i in range(0, len(bits), 16):
                chunk = ", ".join(f"0x{b:02x}" for b in bits[i:i + 16])
                out.write(f"    {chunk},\n")
        index += len(bits)
    out.write("};\n\n")

    out.write("static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {\n")
    out.write("    {.bitmap_index = 0, .adv_w = 0, .box_w = 0, .box_h = 0, "
              ".ofs_x = 0, .ofs_y = 0}, /* id 0 reserved */\n")
    for g, idx in zip(glyphs, indices):
        out.write(f"    {{.bitmap_index = {idx}, .adv_w = {g['adv']}, "
                  f".box_w = {g['w']}, .box_h = {g['h']}, "
                  f".ofs_x = {g['ox']}, .ofs_y = {g['oy']}}},\n")
    out.write("};\n\n")

    for i, cm in enumerate(cmaps):
        out.write(f"static const uint16_t unicode_list_{i}[] = {{\n")
        offs = cm["offsets"]
        for j in range(0, len(offs), 12):
            out.write("    " + ", ".join(f"0x{o:x}" for o in offs[j:j + 12]) + ",\n")
        out.write("};\n\n")

    out.write("static const lv_font_fmt_txt_cmap_t cmaps[] = {\n")
    for i, cm in enumerate(cmaps):
        out.write(f"    {{ .range_start = {cm['range_start']}, "
                  f".range_length = {cm['range_length']}, "
                  f".glyph_id_start = {cm['glyph_id_start']}, "
                  f".unicode_list = unicode_list_{i}, .glyph_id_ofs_list = NULL, "
                  f".list_length = {len(cm['offsets'])}, "
                  f".type = LV_FONT_FMT_TXT_CMAP_SPARSE_TINY }},\n")
    out.write("};\n\n")

    out.write(f"""static const lv_font_fmt_txt_dsc_t font_dsc = {{
    .glyph_bitmap = glyph_bitmap,
    .glyph_dsc = glyph_dsc,
    .cmaps = cmaps,
    .kern_dsc = NULL,
    .kern_scale = 0,
    .cmap_num = {len(cmaps)},
    .bpp = {BPP},
    .kern_classes = 0,
    .bitmap_format = 0,
}};

const lv_font_t {ident} = {{
    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,
    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,
    .line_height = {ascent + descent},
    .base_line = {descent},
    .subpx = LV_FONT_SUBPX_NONE,
    .underline_position = -1,
    .underline_thickness = 1,
    .dsc = &font_dsc,
}};

#endif /* NRL_BOARD_S31_KORVO */
""")
    return out.getvalue()


def main():
    CACHE.mkdir(parents=True, exist_ok=True)
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    if not FONT_FILE.is_file():
        print(f"[cjk_font] downloading {FONT_URL}")
        urllib.request.urlretrieve(FONT_URL, FONT_FILE)

    chars = gb2312_level1_chars() + list(punctuation_chars())
    for size in SIZES:
        font = ImageFont.truetype(str(FONT_FILE), size=size)
        glyphs, ascent, descent = collect_glyphs(font, chars)
        cmaps, ordered = build_cmaps(glyphs)
        name = f"lv_font_cjk_{size}"
        c_text = emit_c(name, size, ordered, cmaps, ascent, descent)
        out_path = OUT_DIR / f"{name}.c"
        out_path.write_text(c_text, encoding="utf-8", newline="\n")
        total_bits = sum(len(g["bits"]) for g in ordered)
        print(f"[cjk_font] {out_path.name}: {len(ordered)} glyphs, "
              f"{total_bits // 1024} KB bitmap, line_height={ascent + descent}")


if __name__ == "__main__":
    sys.exit(main())
