"""Generate the GBK -> Unicode (BMP) lookup table used by media_metadata.cpp.

Legacy Chinese MP3 rips store ID3 text as raw GBK bytes (usually with the
ID3v2 encoding byte claiming ISO-8859-1, or in bare ID3v1 tags). To show
real titles instead of mojibake the firmware converts those bytes to UTF-8
through this table.

Layout: two-byte GBK sequences have lead byte 0x81..0xFE and trail byte
0x40..0xFE (0x7F invalid). The table is a flat uint16 array indexed by
    (lead - 0x81) * 191 + (trail - 0x40)
holding the Unicode code point, or 0 for unassigned pairs. 126*191 entries
= ~48 KB of flash .rodata.

Run from anywhere; rewrites src/media/gbk_unicode_table.generated.h:
    python scripts/gen_gbk_table.py
"""
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "src" / "media" / "gbk_unicode_table.generated.h"

LEAD_FIRST, LEAD_LAST = 0x81, 0xFE
TRAIL_FIRST, TRAIL_LAST = 0x40, 0xFE
TRAIL_SPAN = TRAIL_LAST - TRAIL_FIRST + 1  # 191


def build_table():
    table = []
    for lead in range(LEAD_FIRST, LEAD_LAST + 1):
        for trail in range(TRAIL_FIRST, TRAIL_LAST + 1):
            cp = 0
            if trail != 0x7F:
                try:
                    ch = bytes((lead, trail)).decode("gbk")
                    if len(ch) == 1 and ord(ch) <= 0xFFFF:
                        cp = ord(ch)
                except UnicodeDecodeError:
                    pass
            table.append(cp)
    return table


def main():
    table = build_table()
    assigned = sum(1 for v in table if v)
    lines = [
        "// Generated by scripts/gen_gbk_table.py -- do not edit.",
        "// GBK two-byte sequence -> Unicode BMP code point (0 = unassigned).",
        f"// {assigned} assigned of {len(table)} slots.",
        "#ifndef SRC_MEDIA_GBK_UNICODE_TABLE_GENERATED_H",
        "#define SRC_MEDIA_GBK_UNICODE_TABLE_GENERATED_H",
        "",
        "#include <stdint.h>",
        "",
        f"#define GBK_TABLE_LEAD_FIRST 0x{LEAD_FIRST:02X}u",
        f"#define GBK_TABLE_LEAD_LAST 0x{LEAD_LAST:02X}u",
        f"#define GBK_TABLE_TRAIL_FIRST 0x{TRAIL_FIRST:02X}u",
        f"#define GBK_TABLE_TRAIL_LAST 0x{TRAIL_LAST:02X}u",
        f"#define GBK_TABLE_TRAIL_SPAN {TRAIL_SPAN}u",
        "",
        f"static const uint16_t kGbkToUnicode[{len(table)}] = {{",
    ]
    for i in range(0, len(table), 12):
        chunk = table[i:i + 12]
        lines.append("    " + ", ".join(f"0x{v:04X}" for v in chunk) + ",")
    lines += ["};", "", "#endif", ""]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"[gbk_table] wrote {OUT.name}: {assigned}/{len(table)} assigned")


if __name__ == "__main__":
    main()
